run:
	hspice -i TESTBED.sp -o TESTBED

clean:
	find . -name "*.st*" -type f -delete	
	find . -name "*.ic*" -type f -delete
	find . -name "*.ms*" -type f -delete
	find . -name "*.sw*" -type f -delete
	find . -name "*.log*" -type f -delete
	find . -name "*.mt*" -type f -delete
	find . -name "*.lis*" -type f -delete
	find . -name "*.vcd*" -type f -delete
	find . -name "*.pa*" -type f -delete
	find . -name "*.tr*" -type f -delete
