###################################################################

# Created by write_sdc on Thu Apr 10 13:28:27 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance 1.000000e+04kOhm -capacitance 1.000000e-04pF    \
-voltage V -current uA
set_load -pin_load 0.05 [get_ports {wordline[63]}]
set_load -pin_load 0.05 [get_ports {wordline[62]}]
set_load -pin_load 0.05 [get_ports {wordline[61]}]
set_load -pin_load 0.05 [get_ports {wordline[60]}]
set_load -pin_load 0.05 [get_ports {wordline[59]}]
set_load -pin_load 0.05 [get_ports {wordline[58]}]
set_load -pin_load 0.05 [get_ports {wordline[57]}]
set_load -pin_load 0.05 [get_ports {wordline[56]}]
set_load -pin_load 0.05 [get_ports {wordline[55]}]
set_load -pin_load 0.05 [get_ports {wordline[54]}]
set_load -pin_load 0.05 [get_ports {wordline[53]}]
set_load -pin_load 0.05 [get_ports {wordline[52]}]
set_load -pin_load 0.05 [get_ports {wordline[51]}]
set_load -pin_load 0.05 [get_ports {wordline[50]}]
set_load -pin_load 0.05 [get_ports {wordline[49]}]
set_load -pin_load 0.05 [get_ports {wordline[48]}]
set_load -pin_load 0.05 [get_ports {wordline[47]}]
set_load -pin_load 0.05 [get_ports {wordline[46]}]
set_load -pin_load 0.05 [get_ports {wordline[45]}]
set_load -pin_load 0.05 [get_ports {wordline[44]}]
set_load -pin_load 0.05 [get_ports {wordline[43]}]
set_load -pin_load 0.05 [get_ports {wordline[42]}]
set_load -pin_load 0.05 [get_ports {wordline[41]}]
set_load -pin_load 0.05 [get_ports {wordline[40]}]
set_load -pin_load 0.05 [get_ports {wordline[39]}]
set_load -pin_load 0.05 [get_ports {wordline[38]}]
set_load -pin_load 0.05 [get_ports {wordline[37]}]
set_load -pin_load 0.05 [get_ports {wordline[36]}]
set_load -pin_load 0.05 [get_ports {wordline[35]}]
set_load -pin_load 0.05 [get_ports {wordline[34]}]
set_load -pin_load 0.05 [get_ports {wordline[33]}]
set_load -pin_load 0.05 [get_ports {wordline[32]}]
set_load -pin_load 0.05 [get_ports {wordline[31]}]
set_load -pin_load 0.05 [get_ports {wordline[30]}]
set_load -pin_load 0.05 [get_ports {wordline[29]}]
set_load -pin_load 0.05 [get_ports {wordline[28]}]
set_load -pin_load 0.05 [get_ports {wordline[27]}]
set_load -pin_load 0.05 [get_ports {wordline[26]}]
set_load -pin_load 0.05 [get_ports {wordline[25]}]
set_load -pin_load 0.05 [get_ports {wordline[24]}]
set_load -pin_load 0.05 [get_ports {wordline[23]}]
set_load -pin_load 0.05 [get_ports {wordline[22]}]
set_load -pin_load 0.05 [get_ports {wordline[21]}]
set_load -pin_load 0.05 [get_ports {wordline[20]}]
set_load -pin_load 0.05 [get_ports {wordline[19]}]
set_load -pin_load 0.05 [get_ports {wordline[18]}]
set_load -pin_load 0.05 [get_ports {wordline[17]}]
set_load -pin_load 0.05 [get_ports {wordline[16]}]
set_load -pin_load 0.05 [get_ports {wordline[15]}]
set_load -pin_load 0.05 [get_ports {wordline[14]}]
set_load -pin_load 0.05 [get_ports {wordline[13]}]
set_load -pin_load 0.05 [get_ports {wordline[12]}]
set_load -pin_load 0.05 [get_ports {wordline[11]}]
set_load -pin_load 0.05 [get_ports {wordline[10]}]
set_load -pin_load 0.05 [get_ports {wordline[9]}]
set_load -pin_load 0.05 [get_ports {wordline[8]}]
set_load -pin_load 0.05 [get_ports {wordline[7]}]
set_load -pin_load 0.05 [get_ports {wordline[6]}]
set_load -pin_load 0.05 [get_ports {wordline[5]}]
set_load -pin_load 0.05 [get_ports {wordline[4]}]
set_load -pin_load 0.05 [get_ports {wordline[3]}]
set_load -pin_load 0.05 [get_ports {wordline[2]}]
set_load -pin_load 0.05 [get_ports {wordline[1]}]
set_load -pin_load 0.05 [get_ports {wordline[0]}]
set_ideal_network -no_propagate  [get_ports clk]
create_clock [get_ports clk]  -period 800  -waveform {0 400}
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  400  [get_ports {in_addr[5]}]
set_input_delay -clock clk  400  [get_ports {in_addr[4]}]
set_input_delay -clock clk  400  [get_ports {in_addr[3]}]
set_input_delay -clock clk  400  [get_ports {in_addr[2]}]
set_input_delay -clock clk  400  [get_ports {in_addr[1]}]
set_input_delay -clock clk  400  [get_ports {in_addr[0]}]
set_output_delay -clock clk  400  [get_ports {wordline[63]}]
set_output_delay -clock clk  400  [get_ports {wordline[62]}]
set_output_delay -clock clk  400  [get_ports {wordline[61]}]
set_output_delay -clock clk  400  [get_ports {wordline[60]}]
set_output_delay -clock clk  400  [get_ports {wordline[59]}]
set_output_delay -clock clk  400  [get_ports {wordline[58]}]
set_output_delay -clock clk  400  [get_ports {wordline[57]}]
set_output_delay -clock clk  400  [get_ports {wordline[56]}]
set_output_delay -clock clk  400  [get_ports {wordline[55]}]
set_output_delay -clock clk  400  [get_ports {wordline[54]}]
set_output_delay -clock clk  400  [get_ports {wordline[53]}]
set_output_delay -clock clk  400  [get_ports {wordline[52]}]
set_output_delay -clock clk  400  [get_ports {wordline[51]}]
set_output_delay -clock clk  400  [get_ports {wordline[50]}]
set_output_delay -clock clk  400  [get_ports {wordline[49]}]
set_output_delay -clock clk  400  [get_ports {wordline[48]}]
set_output_delay -clock clk  400  [get_ports {wordline[47]}]
set_output_delay -clock clk  400  [get_ports {wordline[46]}]
set_output_delay -clock clk  400  [get_ports {wordline[45]}]
set_output_delay -clock clk  400  [get_ports {wordline[44]}]
set_output_delay -clock clk  400  [get_ports {wordline[43]}]
set_output_delay -clock clk  400  [get_ports {wordline[42]}]
set_output_delay -clock clk  400  [get_ports {wordline[41]}]
set_output_delay -clock clk  400  [get_ports {wordline[40]}]
set_output_delay -clock clk  400  [get_ports {wordline[39]}]
set_output_delay -clock clk  400  [get_ports {wordline[38]}]
set_output_delay -clock clk  400  [get_ports {wordline[37]}]
set_output_delay -clock clk  400  [get_ports {wordline[36]}]
set_output_delay -clock clk  400  [get_ports {wordline[35]}]
set_output_delay -clock clk  400  [get_ports {wordline[34]}]
set_output_delay -clock clk  400  [get_ports {wordline[33]}]
set_output_delay -clock clk  400  [get_ports {wordline[32]}]
set_output_delay -clock clk  400  [get_ports {wordline[31]}]
set_output_delay -clock clk  400  [get_ports {wordline[30]}]
set_output_delay -clock clk  400  [get_ports {wordline[29]}]
set_output_delay -clock clk  400  [get_ports {wordline[28]}]
set_output_delay -clock clk  400  [get_ports {wordline[27]}]
set_output_delay -clock clk  400  [get_ports {wordline[26]}]
set_output_delay -clock clk  400  [get_ports {wordline[25]}]
set_output_delay -clock clk  400  [get_ports {wordline[24]}]
set_output_delay -clock clk  400  [get_ports {wordline[23]}]
set_output_delay -clock clk  400  [get_ports {wordline[22]}]
set_output_delay -clock clk  400  [get_ports {wordline[21]}]
set_output_delay -clock clk  400  [get_ports {wordline[20]}]
set_output_delay -clock clk  400  [get_ports {wordline[19]}]
set_output_delay -clock clk  400  [get_ports {wordline[18]}]
set_output_delay -clock clk  400  [get_ports {wordline[17]}]
set_output_delay -clock clk  400  [get_ports {wordline[16]}]
set_output_delay -clock clk  400  [get_ports {wordline[15]}]
set_output_delay -clock clk  400  [get_ports {wordline[14]}]
set_output_delay -clock clk  400  [get_ports {wordline[13]}]
set_output_delay -clock clk  400  [get_ports {wordline[12]}]
set_output_delay -clock clk  400  [get_ports {wordline[11]}]
set_output_delay -clock clk  400  [get_ports {wordline[10]}]
set_output_delay -clock clk  400  [get_ports {wordline[9]}]
set_output_delay -clock clk  400  [get_ports {wordline[8]}]
set_output_delay -clock clk  400  [get_ports {wordline[7]}]
set_output_delay -clock clk  400  [get_ports {wordline[6]}]
set_output_delay -clock clk  400  [get_ports {wordline[5]}]
set_output_delay -clock clk  400  [get_ports {wordline[4]}]
set_output_delay -clock clk  400  [get_ports {wordline[3]}]
set_output_delay -clock clk  400  [get_ports {wordline[2]}]
set_output_delay -clock clk  400  [get_ports {wordline[1]}]
set_output_delay -clock clk  400  [get_ports {wordline[0]}]
