gate:
	irun ../00_TESTBED/tb_6to64dec.v -define GATE -debug -v /RAID2/COURSE/2025_Spring/es25MCS/es25MCS042/tech_file/ASAP7_PDKandLIB_v1p5/asap7libs_24/verilog/asap7sc7p5t_24_SIMPLE_RVT_TT.v\
  /RAID2/COURSE/2025_Spring/es25MCS/es25MCS042/tech_file/ASAP7_PDKandLIB_v1p5/asap7libs_24/verilog/asap7sc7p5t_24_SEQ_RVT_TT.v\
  /RAID2/COURSE/2025_Spring/es25MCS/es25MCS042/tech_file/ASAP7_PDKandLIB_v1p5/asap7libs_24/verilog/asap7sc7p5t_24_INVBUF_RVT_TT.v\
 -nontcglitch -loadpli1 debpli:novas_pli_boot
