gate:
	irun ../00_TESTBED/decoder_6to64_tb.v -define GATE -debug -v /RAID2/COURSE/2025_Spring/es25MCS/es25MCS042/tech_file/ASAP7_PDKandLIB_v1p5/asap7libs_24/verilog/asap7sc7p5t_24_SIMPLE_SRAM_TT.v\
  /RAID2/COURSE/2025_Spring/es25MCS/es25MCS042/tech_file/ASAP7_PDKandLIB_v1p5/asap7libs_24/verilog/asap7sc7p5t_24_SEQ_SRAM_TT.v\
  /RAID2/COURSE/2025_Spring/es25MCS/es25MCS042/tech_file/ASAP7_PDKandLIB_v1p5/asap7libs_24/verilog/asap7sc7p5t_24_INVBUF_SRAM_TT.v\
 -nontcglitch -loadpli1 debpli:novas_pli_boot

clean:
	rm -rf INCA_libs
	rm -rf *.log
	rm -rf *.history
	rm -rf *.fsdb
